export const disabilityOptions = [
  { value: 'autism', label: 'Autism' },
  { value: 'intellectual-disability', label: 'Intellectual Disability' },
  { value: 'psychosocial-disability', label: 'Psychosocial Disability' },
  { value: 'development-delay', label: 'Development delay' },
  { value: 'global-development-delay', label: 'Global development delay' },
  { value: 'cerebral-palsy', label: 'Cerebral Palsy' },
  { value: 'down-syndrome', label: 'Down Syndrome' },
  { value: 'hearing-impairment', label: 'Hearing Impairment' },
  { value: 'visual-impairment', label: 'Visual Impairment' },
  { value: 'acquired-brain-injury', label: 'Acquired Brain Injury' },
  { value: 'spinal-cord-injury', label: 'Spinal Cord Injury' },
  { value: 'stroke', label: 'Stroke' },
  { value: 'multiple-sclerosis', label: 'Multiple Sclerosis' },
  { value: 'parkinsons', label: 'Parkinsons' },
  { value: 'motor-neurone-disease', label: 'Motor Neurone Disease' },
  { value: 'other', label: 'Other' },
  { value: 'prefer-not-to-say', label: 'Prefer not to say' },
]
